# Generated by Django 4.2.13 on 2024-06-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0002_alter_country_options_rename_iso_code_country_iso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
    ]
