# Generated by Django 4.2.13 on 2024-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_app', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.CharField(max_length=100),
        ),
    ]
